version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: licitalab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./licitalab-backend2
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/licitalab
      - PORT=4000
      - JWT_SECRET=tu_secreto_muy_largo_y_seguro
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./licitalab-opportunities
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=tu_clave_secreta_segura
      - DOCKER_ENVIRONMENT=true
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
